version: "3.9"

services:
  ml-api:
    build:
      context: ../ml
    image: gallifrey-ml-api
    container_name: gallifrey-ml-api
    ports:
      - "8000:8000"
    volumes:
      - ../ml/data/models:/app/data/models:ro
      - ../ml/data:/app/data:ro

  ml-mock:
    build:
      context: ../ml/mock
    image: gallifrey-ml-mock
    container_name: gallifrey-ml-mock
    depends_on:
      - ml-api
    environment:
      - MOCK_SERVER_URL=ws://ml-api:8000/ws/anomaly

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infra_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescaledb_data:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana


  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  timescaledb_data:
  grafana_data:
  chroma_data: