from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


RESULTS_DIR = Path(__file__).resolve().parent / "results"
FIGURES_DIR = Path(__file__).resolve().parent / "figures"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)


def plot_anomaly_timeseries(results_path: Path | None = None) -> Path:
    """
    Plot anomaly-related metrics over time from the results CSV generated by
    the streaming client and save the figure under mock/figures/.
    """
    if results_path is None:
        results_path = RESULTS_DIR / "stream_results.csv"

    df = pd.read_csv(results_path, parse_dates=["timestamp"])
    df = df.sort_values("timestamp")

    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

    # Strain with anomaly flags
    axes[0].plot(
        df["timestamp"],
        df["strain_microstrain"],
        label="Strain (microstrain)",
        color="tab:blue",
    )
    axes[0].scatter(
        df.loc[df["is_anomaly"], "timestamp"],
        df.loc[df["is_anomaly"], "strain_microstrain"],
        color="tab:red",
        label="Detected anomaly",
        s=10,
    )
    axes[0].set_ylabel("Strain (microstrain)")
    axes[0].legend(loc="upper left")
    axes[0].set_title("Strain and detected anomalies")

    # Isolation Forest score
    axes[1].plot(
        df["timestamp"], df["if_score"], label="Isolation Forest score", color="tab:green"
    )
    axes[1].set_ylabel("IF score")
    axes[1].legend(loc="upper left")

    # Reconstruction error (if available)
    if "recon_error" in df.columns and df["recon_error"].notna().any():
        axes[2].plot(
            df["timestamp"],
            df["recon_error"],
            label="Reconstruction error",
            color="tab:orange",
        )
        axes[2].set_ylabel("Recon. error")
        axes[2].legend(loc="upper left")
    else:
        axes[2].text(
            0.5,
            0.5,
            "No reconstruction error available",
            transform=axes[2].transAxes,
            ha="center",
            va="center",
        )
    axes[2].set_xlabel("Time")

    fig.autofmt_xdate()
    fig.tight_layout()

    out_path = FIGURES_DIR / "anomaly_timeseries.png"
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Saved visualization to {out_path}")
    return out_path


def main() -> None:
    plot_anomaly_timeseries()


if __name__ == "__main__":
    main()

